from src.tabs.sacn import build_sacn_tab
from src.tabs.generator import build_generator_tab
from src.tabs.groups import build_groups_tab
from src.tabs.schedule import build_schedule_tab
from src.tabs.flags import build_flags_tab
from src.tabs.chases import build_chases_tab
from src.tabs.country_editor import build_country_editor_tab
from src.tabs.readme_tab import build_readme_tab
from src.tabs.api import build_api_tab
